### PR TITLE
feat: pricing

### LINKED ISSUE #2: Create registration page
Create the registration page similar to: https://bpm2024.agh.edu.pl/registration/ with the following prices:

|                       |                    |                     |                    |
| --------------------- | ------------------ | ------------------- | ------------------ |
|                      | until 15 Jan 2025 | until 14 July 2025 | until 15 Aug 2025 |
| Main Conference Only | 550               | 600                | 650               |
| Workshops Only       | 240               | 280                | 350               |
| Main+Workshops       | 650               | 700                | 750               |
| Day Ticket           |                   |                    | 400               |

### PR DESCRIPTION
**Pull request by ferferga**
Closes #2 

@resinas Does this look good to you? Is my assumption (day only ticket only applies to conference), correct?

I'd also like to know if it would be possible to purchase tickets during the conference (like in Krakow with the extra fee) and the refunding details, since that could give me a grasp of how to continue iterating this page going forward.

### CODE REVIEW

**Comment by resinas** [comment]
It's a nice approach, but there are several things that need to be changed:
- The price is too big. The type of registration should be the same size or bigger (see https://www.dropbox.com/plans for instance).
- The prices that do not apply now should be smaller than the price that is active at this moment.
- Since we have four options, it would be great if the four of them could fit in the same row.
- The list of options that each registration type offer should be as follows:

All workshop sessions (1 September)
All conference sessions (2-4 September)
Reception (1 September)
Guided tour (2 September)
Conference dinner (3 September)
Conference bag

The workshops option will have the first one, the reception and the conference bag
The conference only will have all of them except for workshop sessions
The conference + workshops will have all of them
The daily ticket, since it is very different, could have just these two:
- Conference sessions (only the day of the ticket)
- Social event (only the day of the ticket)

In addition, you need to add additional information about students registration and cancellation policy. You can copy the canecllation policy from here: https://conferences.big.tuwien.ac.at/caise2025/register.php

Concerning the students, you just need to mention that:

- We offer a 100€ discount for students. If you register as a student, you must provide proof of your student status (e.g. a student card including the academic year). You are eligible for the ‘Student fee’ if you are a student in the academic year 2024-2025. In case you are not able to provide a proof in time, your student registration will be automatically changed into a regular registration, and you will be charged accordingly. 
- If you are a MSc/PhD student and the presenting author (i.e., the only one among the authors who is present at the event) of a paper accepted at a workshop/co-located event/main conference, then you need to buy a regular registration, regardless of whether or not you are a student.
- If you are a PhD student and you have been accepted to participate in the Doctoral Consortium, the participation to the Doctoral Consortium is free of charge. If you want to attend the rest of the workshops and/or conference, you can register as a student.

**Review by resinas — CHANGES_REQUESTED** [review]
Just added a detailed comment with the suggested changes in the pull request

**Comment by ferferga** [comment]
@resinas Please check it now, I hope it's better!

**Review by resinas — APPROVED** [review]
I changed the code to put all price boxes in the same row, and now we are good to go.

**Pull request merged**
